# Generated by Django 2.1.3 on 2019-09-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_workupdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workupdates',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
