# Generated by Django 2.2.5 on 2019-11-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20191118_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='training_id',
        ),
    ]
